"""Generate ``docs/policy_table.md`` from the policy engine (team decision of 8 Oct 2026).

    python -m gbya.policy.table         # make policy-table

Every combination of state-changing tool, host tier, account type, privilege and dependents is
evaluated by
the real engine on a synthetic trusted context; the table shows the decision, the winning rule
and every matching rule. Combinations that fall through to the default are flagged. A test
regenerates the table and fails if the committed copy differs.
"""

from __future__ import annotations

from itertools import product
from pathlib import Path
from typing import Any

from gbya.config import REPO_ROOT
from gbya.context.models import TrustedContext
from gbya.policy.engine import PolicyEngine, load_evidence_requirements
from gbya.tools.names import STATE_CHANGING

RULES = REPO_ROOT / "policy" / "rules.yaml"
EVIDENCE = REPO_ROOT / "policy" / "evidence_requirements.yaml"
OUT = REPO_ROOT / "docs" / "policy_table.md"

TIERS = (0, 1, 2)
TYPES = ("human", "service")
PRIVILEGES = ("standard", "admin", "domain_admin")
DEPENDENTS = ("empty", "nonempty")
# The attributes each tool's arguments name (the others cannot influence its decision).
USES = {
    "isolate_host": ("tier",),
    "kill_process": ("tier",),
    "disable_account": ("type", "privilege", "dependents"),
    "block_ip": (),
}


def _context(tier: int, acct_type: str, privilege: str, deps: str) -> TrustedContext:
    return TrustedContext.model_validate(
        {
            "schema_version": 1,
            "assets": [{"host": "target-host", "role": "test", "tier": tier}],
            "identities": [
                {
                    "account": "target-account",
                    "type": acct_type,
                    "privilege": privilege,
                    "dependents": ["dependent-service"] if deps == "nonempty" else [],
                }
            ],
            "network": {"internal_cidrs": ["10.0.0.0/8"]},
            "approval_script": {"mode": "unreachable"},
        }
    )


ARGS: dict[str, dict[str, Any]] = {
    "isolate_host": {"host": "target-host"},
    "kill_process": {"host": "target-host", "pid": 4242},
    "disable_account": {"account": "target-account"},
    "block_ip": {"ip": "203.0.113.7"},
}


def rows(engine: PolicyEngine) -> list[dict[str, Any]]:
    out = []
    for tool, tier, t, p, d in product(STATE_CHANGING, TIERS, TYPES, PRIVILEGES, DEPENDENTS):
        ctx = _context(tier, t, p, d)
        decision = engine.evaluate(tool, ARGS[tool], ctx)
        matched = [r.id for r in engine.matching_rules(tool, ARGS[tool], ctx)]
        out.append(
            {
                "tool": tool,
                "tier": tier,
                "type": t,
                "privilege": p,
                "dependents": d,
                "decision": decision.decision,
                "rule": decision.rule_id,
                "matched": matched,
            }
        )
    return out


def render(engine: PolicyEngine, evidence: dict[str, str]) -> str:
    all_rows = rows(engine)
    lines = [
        "# Policy table (C5)\n",
        "Generated by `make policy-table` from `policy/rules.yaml` with the real policy engine; "
        "do not edit by hand (a test fails if this file differs from a fresh generation). "
        "Signed off by the team on 8 October 2026; **frozen once dev tuning starts**.\n",
        "Semantics: a rule matches when all its conditions hold; if several match, the "
        "**strictest decision wins** (forbidden > needs_approval > allowed; ties report the "
        "first rule in file order); with no match the default is "
        f"**{engine.policy.default}**. Reversibility (proposal §8) enters through "
        "`action.reversible`: irreversible actions (`kill_process`) are allowed on tier-2 hosts "
        "and need approval on tiers 0 and 1. Hosts or accounts missing from the trusted context "
        "also fall to the default, but C1 rejects such calls first (`C1_UNKNOWN_HOST`, "
        "`C1_UNKNOWN_ACCOUNT`).\n",
        "## Combinations that fall through to the default\n",
    ]
    fall = [r for r in all_rows if r["rule"] == "default"]
    if not fall:
        lines.append("None: every combination is decided by a rule.\n")
    else:
        lines.append("| Tool | Tier | Account type | Privilege | Dependents | Decision |")
        lines.append("|---|---:|---|---|---|---|")
        lines += [
            f"| {r['tool']} | {r['tier']} | {r['type']} | {r['privilege']} | {r['dependents']} "
            f"| **{r['decision']}** (default) |"
            for r in fall
        ]
        lines.append("")

    lines.append("## Summary by tool (only the attributes the tool's arguments name)\n")
    lines.append("| Tool | Attributes | Decision | Rule |")
    lines.append("|---|---|---|---|")
    seen: set[tuple[str, tuple[Any, ...]]] = set()
    for r in all_rows:
        key = (r["tool"], tuple(r[a] for a in USES[r["tool"]]))
        if key in seen:
            continue
        seen.add(key)
        attrs = ", ".join(f"{a}={r[a]}" for a in USES[r["tool"]]) or "(none)"
        lines.append(f"| {r['tool']} | {attrs} | {r['decision']} | {r['rule']} |")
    lines.append("")

    lines.append(
        f"## Full grid ({len(all_rows)} combinations of tool, tier, account type, privilege and "
        "dependents)\n"
    )
    lines.append(
        "| Tool | Tier | Account type | Privilege | Dependents | Decision | Rule "
        "| All matching rules |"
    )
    lines.append("|---|---:|---|---|---|---|---|---|")
    for r in all_rows:
        flag = " ⚠ default" if r["rule"] == "default" else ""
        lines.append(
            f"| {r['tool']} | {r['tier']} | {r['type']} | {r['privilege']} | {r['dependents']} "
            f"| {r['decision']}{flag} | {r['rule']} | {', '.join(r['matched']) or '—'} |"
        )
    lines.append("")

    lines.append("## Evidence requirements (given verbatim to the C4 verifier)\n")
    for tool in STATE_CHANGING:
        lines.append(f"**{tool}**: {evidence[tool]}\n")
    return "\n".join(lines)


def generate(rules: Path = RULES, evidence: Path = EVIDENCE) -> str:
    return render(PolicyEngine.from_file(rules), load_evidence_requirements(evidence))


def main() -> None:
    OUT.write_text(generate())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
