"""Render ``docs/splits.md`` from ``data/splits.json`` (T1.6, team decision of 8 Oct 2026).

    python -m gbya.data.splits_doc            # make splits-doc

Sections: tactic counts per split; every window with its title, primary tactic, split,
de-duplication group, primary host and that host's share of events; and, for dev and test
windows, whether any record on the primary host names an acting user (needed by C3 for
``disable_account``).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from gbya.data.catalogue import TACTIC_NAMES
from gbya.data.window_stats import ActingUsers

SPLITS = ("dev", "test", "e2e", "unused")


def _md(text: object) -> str:
    return str(text).replace("|", "\\|")


def render(
    doc: dict[str, Any],
    titles: dict[str, str],
    acting: dict[str, ActingUsers],
    splits_sha256: str,
    notes: list[str],
) -> str:
    windows: dict[str, dict[str, Any]] = doc["windows"]
    out: list[str] = []
    out.append("# Window splits (T1.6)\n")
    out.append(
        "Generated by `make splits-doc` from `data/splits.json` "
        f"(SHA-256 `{splits_sha256}`). Accepted by the team on 8 October 2026.\n"
    )
    out.append(
        f"Seed {doc['seed']}; OTRF commit `{doc.get('otrf_commit', '?')}`; targets "
        + ", ".join(f"{k} {v}" for k, v in doc["targets"].items())
        + f". Method: {doc['method']}\n"
    )

    out.append("## Tactic counts per split (primary tactic)\n")
    tactics = sorted({t for cov in doc["tactic_coverage"].values() for t in cov})
    out.append("| Tactic | " + " | ".join(SPLITS) + " | total |")
    out.append("|---|" + "---:|" * (len(SPLITS) + 1))
    for t in tactics:
        counts = [doc["tactic_coverage"].get(s, {}).get(t, 0) for s in SPLITS]
        out.append(f"| {t} | " + " | ".join(map(str, counts)) + f" | {sum(counts)} |")
    totals = [len(doc["splits"].get(s, [])) for s in SPLITS]
    out.append("| **total** | " + " | ".join(map(str, totals)) + f" | {sum(totals)} |\n")

    out.append("## Windows\n")
    out.append(
        "Primary host = the host with the most `process_create` + `process_access` events; "
        "share = its fraction of all the window's events (multi-host windows have a low share).\n"
    )
    out.append(
        "| Window | Title | Primary tactic | Split | De-dup group | Primary host "
        "| Host share | Events |"
    )
    out.append("|---|---|---|---|---|---|---:|---:|")
    order = {s: i for i, s in enumerate(SPLITS)}
    group_size: dict[str, int] = {}
    for w in windows.values():
        group_size[w["dedup_group"]] = group_size.get(w["dedup_group"], 0) + 1
    for wid, w in sorted(windows.items(), key=lambda kv: (order.get(kv[1]["split"], 9), kv[0])):
        group = f"`{w['dedup_group']}`" if group_size[w["dedup_group"]] > 1 else "—"
        share = w.get("primary_host_share")
        out.append(
            f"| `{wid}` | {_md(titles.get(wid, ''))} | "
            f"{TACTIC_NAMES.get(w['primary_tactic'], w['primary_tactic'])} | {w['split']} | "
            f"{group} | {_md(w.get('primary_host') or '—')} | "
            f"{'—' if share is None else f'{share:.0%}'} | {w.get('events', '—')} |"
        )
    out.append("")

    out.append("## Acting user on the primary host (dev and test windows)\n")
    out.append(
        "C3 for `disable_account(U)` needs a cited record whose acting-user field equals U "
        "(field per table: `docs/fieldmap.md`). *Names an acting user* = at least one record on "
        "the primary host has that field set. *Non-built-in accounts* excludes SYSTEM, LOCAL/"
        "NETWORK SERVICE, ANONYMOUS LOGON, DWM-*/UMFD-* and machine accounts (`…$`), which are "
        "not realistic accounts to disable.\n"
    )
    out.append(
        "| Window | Split | Names an acting user | Records | By table "
        "| Non-built-in accounts (records) |"
    )
    out.append("|---|---|---|---:|---|---|")
    for split in ("dev", "test"):
        for wid in doc["splits"][split]:
            a = acting[wid]
            tables = ", ".join(f"{t} {n}" for t, n in a.by_table.items()) or "—"
            nb = ", ".join(f"`{_md(u)}` ({n})" for u, n in a.non_builtin.items()) or "none"
            out.append(
                f"| `{wid}` | {split} | {'yes' if a.records else '**no**'} | {a.records} | "
                f"{tables} | {nb} |"
            )
    yes = sum(1 for s in ("dev", "test") for w in doc["splits"][s] if acting[w].records)
    nb_yes = sum(1 for s in ("dev", "test") for w in doc["splits"][s] if acting[w].non_builtin)
    n_all = sum(len(doc["splits"][s]) for s in ("dev", "test"))
    out.append(
        f"\nSummary: {yes} of {n_all} dev+test windows name an acting user on the primary host; "
        f"{nb_yes} name at least one non-built-in account.\n"
    )

    if notes:
        out.append("## Notes\n")
        out.extend(f"- {n}" for n in notes)
        out.append("")
    return "\n".join(out)


NOTES = [
    "`collection` has a single eligible window; its proportional quota rounds to 0 in every "
    "split, so the tactic is in no split. To be listed in the final report's limitations.",
    'SDWIN-230718150800 ("Dumping NTDS.dit from Volume Shadow Copy") is excluded: its Host '
    "file `cmd_copy_ntds_from_volume_shadow_copy.zip` does not exist at the pinned commit; a "
    "similarly named file is deliberately not substituted. 99 of the 100 windows were ingested.",
    "De-duplication pairs (J > 0.5) are different attacks recorded in the same lab sessions; "
    "shared background events push their similarity over 0.5. Grouping only keeps each pair in "
    "the same split (the cautious side).",
    "The LSASS demo window (SDWIN-201018225619) is `unused`, so the demo fixture does not reuse a "
    "research window.",
]


def main() -> None:
    from sqlalchemy import select

    from gbya.config import REPO_ROOT, get_settings
    from gbya.data.connection import open_case_db
    from gbya.data.window_stats import acting_users
    from gbya.store.db import make_engine, make_sessionmaker, session_scope
    from gbya.store.models import Window

    settings = get_settings()
    splits_path = settings.resolve(settings.data_dir) / "splits.json"
    raw = splits_path.read_bytes()
    doc = json.loads(raw)
    factory = make_sessionmaker(make_engine())
    with session_scope(factory) as s:
        rows = {w.id: w for w in s.scalars(select(Window)).all()}
    titles = {wid: w.title for wid, w in rows.items()}
    acting: dict[str, ActingUsers] = {}
    for split in ("dev", "test"):
        for wid in doc["splits"][split]:
            path = rows[wid].duckdb_path
            assert path is not None
            con = open_case_db(settings.resolve(Path(path)))
            try:
                acting[wid] = acting_users(con, doc["windows"][wid]["primary_host"])
            finally:
                con.close()
    text = render(doc, titles, acting, hashlib.sha256(raw).hexdigest(), NOTES)
    out = REPO_ROOT / "docs" / "splits.md"
    out.write_text(text)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
